// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3e11Q_AQ7JN7Io5WZQdoUKOsraDUS78E',
    appId: '1:913452332468:web:9ce09bc4377d4398282ee1',
    messagingSenderId: '913452332468',
    projectId: 'chatter-36175',
    authDomain: 'chatter-36175.firebaseapp.com',
    storageBucket: 'chatter-36175.appspot.com',
    measurementId: 'G-DJH2JWWLQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGsDaay-x7QQUnuphkTYSZmfLNxocl5V4',
    appId: '1:913452332468:android:c69a930d88297660282ee1',
    messagingSenderId: '913452332468',
    projectId: 'chatter-36175',
    storageBucket: 'chatter-36175.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTAGZl_okXYaYJVDBf6OFnMz_IquLAu98',
    appId: '1:913452332468:ios:fcc8ef68e3ad2892282ee1',
    messagingSenderId: '913452332468',
    projectId: 'chatter-36175',
    storageBucket: 'chatter-36175.appspot.com',
    androidClientId: '913452332468-3mhlvf2qpapm0t5dqptpkp607jb6vvtl.apps.googleusercontent.com',
    iosClientId: '913452332468-f1s8sq9b435b4cvdaq3vt1jblhjdcrm5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatter',
  );

}